export const START_LOADING = 'START_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'

export const SIDEMENU_COMPLETE = 'SIDEMENU_COMPLETE'

export const MODAL_STATE = 'MODAL_STATE'

//店铺列表
export const GET_SHOP_LIST = 'GET_SHOP_LIST'
export const GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS'
//店铺详情
export const GET_SHOP_DETAIL = 'GET_SHOP_DETAIL'
export const GET_SHOP_DETAIL_SUCCESS = 'GET_SHOP_DETAIL_SUCCESS'
//获取支付密钥
export const GET_PAYSRCRET = 'GET_PAYSRCRET'
export const GET_PAYSRCRET_SUCCESS = 'GET_PAYSRCRET_SUCCESS'
//删除店铺
export const DELETE_SHOP = 'DELETE_SHOP'