export const START_LOADING = 'START_LOADING'
export const CLOSE_LOADING = 'CLOSE_LOADING'

export const SIDEMENU_COMPLETE = 'SIDEMENU_COMPLETE'

export const MODAL_STATE = 'MODAL_STATE'
export const SELECT_LOAD = 'SELECT_MODAL'

//店铺列表
export const GET_SHOP_LIST = 'GET_SHOP_LIST'
export const GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS'
//店铺详情
export const GET_SHOP_DETAIL = 'GET_SHOP_DETAIL'
export const GET_SHOP_DETAIL_SUCCESS = 'GET_SHOP_DETAIL_SUCCESS'
//获取支付密钥
export const GET_PAYSRCRET = 'GET_PAYSRCRET'
export const GET_PAYSRCRET_SUCCESS = 'GET_PAYSRCRET_SUCCESS'
//删除店铺
export const DELETE_SHOP = 'DELETE_SHOP'
//店铺权限
export const GET_SHOPPERM = 'GET_SHOPPERM'
export const GET_SHOPPERM_SUCCESS = 'GET_SHOPPERM_SUCCESS'
//修改店铺权限
export const CHANGE_SHOPPERM = 'CHANGE_SHOPPERM'
//获取行业列表
export const GET_INDUSTRY = 'GET_INDUSTRY'
export const GET_INDUSTRY_SUCCESS = 'GET_INDUSTRY_SUCCESS'
//地区
export const GET_AREA = 'GET_AREA'
export const GET_AREA_SUCCESS = 'GET_AREA_SUCCESS'
//修改店铺
export const CHANGE_SHOPDETAIL = 'CHANGE_SHOPDETAIL'
//店铺账号详情
export const GET_ACCOUNT_DETAIL = 'GET_ACCOUNT_DETAIL'
export const GET_ACCOUNT_DETAIL_SUCCESS = 'GET_ACCOUNT_DETAIL_SUCCESS'
//修改店铺账号
export const CHANGE_SHOP_ACCOUNT = 'CHANGE_SHOP_ACCOUNT'
//初次加载账单页面
export const BILL_PRIMARY_LOAD = 'BILL_PRIMARY_LOAD'
//获取账单列表
export const GET_BILLLIST = 'GET_BILLLIST'
export const GET_BILLLIST_SUCCESS = 'GET_BILLLIST_SUCCESS'
//获取今日交易金额和笔数
export const GET_TODAYTOTAL = 'GET_TODAYTOTAL'
export const GET_TODAYTOTAL_SUCCESS = 'GET_TODAYTOTAL_SUCCESS'
//筛选账单
export const FILTER_BILL = 'FILTER_BILL'
//账单详情
export const GET_BILLDETAIL = 'GET_BILLDETAIL'
export const GET_BILLDETAIL_SUCCESS = 'GET_BILLDETAIL_SUCCESS'
